### ISSUE TITLE
flexMenu with Bootstrap v4 Tabs

### ISSUE THREAD

**Issue by bulutozturk1993** [352Media/flexMenu#42] opened 2018-02-22 09:07 UTC
Hello,

I use flexMenu with Bootstrap v4 tabs but have a problem. Tabs are opening but they aren't closing. I added extra jQuery code;

`$(document).on('click', 'li.flexMenu-viewMore', function(){
	$('li.flexMenu-viewMore li a.active').removeClass('active show');
	$(this).addClass('active show');
});`

Live demo: http://demo.gloriathemes.com/wp/eventchamp/

Kind regards.

**Comment by rdebeasi** [comment] 2018-02-23 22:21
Thanks for getting in touch!

What you described seems to be the intended behavior of Bootstrap's tabs. Their [example code](https://getbootstrap.com/docs/4.0/components/navs/#javascript-behavior) shows tabs that open when you click them but do not close when you click them a second time.

I'm going to close this issue because as far as I can tell, flexMenu isn't causing this behavior. Sorry I can't be more helpful here!

**Closed by rdebeasi** 2018-02-23 22:21 UTC
